dotfiles:
  - .github/**/*
  - .gitignore
  - .editorconfig

recipes:
  - src/brew_bot/calculators.cljc
  - src/brew_bot/generators.cljc
  - src/brew_bot/ingredients.cljc
  - src/brew_bot/weights.cljc

restricted:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE

test-dependencies:
  - package.json
  - package-lock.json
